<a href="https://colab.research.google.com/github/mooncpark/nfl_fantasy_prediction/blob/main/Dashboard_POC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Proof of Concept

[MVP Mock](https://lookerstudio.google.com/u/1/reporting/b9277c40-6df9-48d2-9cbf-346c0c52b8f3/page/iUELD)

1. Take the output of our models (dataframe) and export to drive
2. Schedule the colab to run daily and overwrite the drive csv or spreadsheet for freshness
3. Connect Data Studio to export file as MVP

---

### Method 1: Overwriting CSVs in Drive

In [ ]:
# Imports
import pandas as pd
from google.colab import drive

In [ ]:
# Create a dummy dataframe to replicate the modeling output
drive.mount('/content/drive')
sample_data = pd.read_csv('/content/drive/Shareddrives/NFL Project/project_sample_data.csv')
sample_data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,week,player,team,position,standard_points,half_ppr_points,ppr_points
0,1,Christian McCaffrey,SF,RB,17.0,20.40,25.50
1,1,Saquon Barkley,NYG,RB,16.7,20.04,25.05
2,1,James Conner,ARI,RB,15.7,18.84,23.55
3,1,Justin Jefferson,MIN,WR,15.1,18.12,22.65
4,1,Travis Etienne Jr.,JAC,RB,14.7,17.64,22.05

In [ ]:
# Introduce changes
sample_data['standard_points'] = sample_data['standard_points'] + 1
sample_data['half_ppr_points'] = sample_data['standard_points'] * 1.2
sample_data['ppr_points'] = sample_data['standard_points'] * 1.5
sample_data.head()

,week,player,team,position,standard_points,half_ppr_points,ppr_points
0,1,Christian McCaffrey,SF,RB,19.0,22.80,28.50
1,1,Saquon Barkley,NYG,RB,18.7,22.44,28.05
2,1,James Conner,ARI,RB,17.7,21.24,26.55
3,1,Justin Jefferson,MIN,WR,17.1,20.52,25.65
4,1,Travis Etienne Jr.,JAC,RB,16.7,20.04,25.05

In [ ]:
# Overwrite the existing CSV with a new dataframe
sample_data.to_csv('/content/drive/Shareddrives/NFL Project/project_sample_data.csv')

In [ ]:
# Make sure the changes are reflected in the overwritten file
sample_data_2 = pd.read_csv('/content/drive/Shareddrives/NFL Project/project_sample_data.csv')
sample_data_2.head()

,Unnamed: 0,week,player,team,position,standard_points,half_ppr_points,ppr_points
0,0,1,Christian McCaffrey,SF,RB,19.0,22.80,28.50
1,1,1,Saquon Barkley,NYG,RB,18.7,22.44,28.05
2,2,1,James Conner,ARI,RB,17.7,21.24,26.55
3,3,1,Justin Jefferson,MIN,WR,17.1,20.52,25.65
4,4,1,Travis Etienne Jr.,JAC,RB,16.7,20.04,25.05

---

### Method 2: Overwriting Spreadsheet in Drive

In [ ]:
# Overwrite existing spreadsheet with a new dataframe

sample_data.to_drive('/content/drive/Shareddrives/NFL Project/project_sample_data')

AttributeError: ignored

---

### Scheduling

In [ ]:
!git clone https://github.com/bitnom/colabctl.git

Cloning into 'colabctl'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (20/20), done.
remote: Total 118 (delta 19), reused 19 (delta 19), pack-reused 98
Receiving objects: 100% (118/118), 41.93 KiB | 2.47 MiB/s, done.
Resolving deltas: 100% (64/64), done.

Our original design planned to use clbctl.py as method to schedule this job daily without having to pay for cloud compute resources. Unfortunately, the package looks to be deprecated now so we will explore the following options:

* Upgrade Colab to Pro+ ($50/month) to use native scheduling 
* Use Google Cloud Scheduler + GCF to schedule the job daily
* Figure out how to manually schedule a workflow from local machine
* Demonstrate the proof of concept in the capstone project without implementing the scheduled workflow.

We will try to explore option 3, but will most likely move forward with #4 instead of paying for a solution (given we understand how to get the workflow started with payment).